-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;

-- Table: freeler.asignaciones
CREATE TABLE IF NOT EXISTS freeler.asignaciones
(
    id_asignacion integer NOT NULL DEFAULT nextval('freeler.asignaciones_id_asignacion_seq'::regclass),
    id_lead integer NOT NULL,
    id_usuario_empresa integer NOT NULL,
    fecha_asignacion timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    id_asignado_usuario_empresa integer NOT NULL,
    id_estado_lead integer NOT NULL,
    estado integer DEFAULT 1 COLLATE pg_catalog."default", -- 1: Activo, 0: Inactivo
    CONSTRAINT asignaciones_pkey PRIMARY KEY (id_asignacion),
    CONSTRAINT asignaciones_id_asignado_usuario_empresa_fkey FOREIGN KEY (id_asignado_usuario_empresa)
        REFERENCES freeler.usuarios_empresa (id_usuario_empresa) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT asignaciones_id_estado_lead_fkey FOREIGN KEY (id_estado_lead)
        REFERENCES freeler.estado_lead (id_estado_lead) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT asignaciones_id_lead_fkey FOREIGN KEY (id_lead)
        REFERENCES freeler.leads (id_lead) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT asignaciones_id_usuario_empresa_fkey FOREIGN KEY (id_usuario_empresa)
        REFERENCES freeler.usuarios_empresa (id_usuario_empresa) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS freeler.asignaciones
    OWNER to postgres;

-- Index: fki_asignaciones_id_asignado_usuario_empresa_fkey
CREATE INDEX IF NOT EXISTS fki_asignaciones_id_asignado_usuario_empresa_fkey
    ON freeler.asignaciones USING btree
    (id_asignado_usuario_empresa ASC NULLS LAST)
    WITH (fillfactor=100, deduplicate_items=True)
    TABLESPACE pg_default;
-- Index: fki_asignaciones_id_estado_lead_fkey
CREATE INDEX IF NOT EXISTS fki_asignaciones_id_estado_lead_fkey
    ON freeler.asignaciones USING btree
    (id_estado_lead ASC NULLS LAST)
    WITH (fillfactor=100, deduplicate_items=True)
    TABLESPACE pg_default;


-- Table: freeler.campanias
CREATE TABLE IF NOT EXISTS freeler.campanias
(
    id_campania serial NOT NULL,
    id_empresa integer,
    nombre character varying COLLATE pg_catalog."default" NOT NULL,
    descripcion text COLLATE pg_catalog."default",
    ubicacion character varying COLLATE pg_catalog."default",
    comision numeric(10, 2) NOT NULL,
    fecha_inicio date NOT NULL,
    fecha_fin date NOT NULL,
    estado integer DEFAULT 1,
    fecha_creacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT campanias_pkey PRIMARY KEY (id_campania)
);

CREATE TABLE IF NOT EXISTS freeler.comisiones
(
    id_comision serial NOT NULL,
    id_lead integer,
    id_usuario_freeler integer,
    id_campania integer,
    monto numeric(10, 2) NOT NULL,
    id_estado_comision integer,
    fecha_pago timestamp without time zone,
    CONSTRAINT comisiones_pkey PRIMARY KEY (id_comision)
);

CREATE TABLE IF NOT EXISTS freeler.empresas
(
    id_empresa serial NOT NULL,
    razon_social character varying COLLATE pg_catalog."default" NOT NULL,
    ruc character varying COLLATE pg_catalog."default" NOT NULL,
    direccion character varying COLLATE pg_catalog."default",
    telefono character varying COLLATE pg_catalog."default",
    email character varying COLLATE pg_catalog."default",
    representante_legal character varying COLLATE pg_catalog."default",
    estado integer DEFAULT 1,
    fecha_creacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT empresas_pkey PRIMARY KEY (id_empresa)
);

CREATE TABLE IF NOT EXISTS freeler.estado_comisiones
(
    id_estado_comision serial NOT NULL,
    nombre character varying COLLATE pg_catalog."default" NOT NULL,
    descripcion text COLLATE pg_catalog."default",
    CONSTRAINT estado_comisiones_pkey PRIMARY KEY (id_estado_comision)
);

CREATE TABLE IF NOT EXISTS freeler.estado_lead
(
    id_estado_lead serial NOT NULL,
    nombre character varying COLLATE pg_catalog."default" NOT NULL,
    descripcion text COLLATE pg_catalog."default",
    CONSTRAINT estado_lead_pkey PRIMARY KEY (id_estado_lead)
);

CREATE TABLE IF NOT EXISTS freeler.leads
(
    id_lead serial NOT NULL,
    id_campania integer,
    id_usuario_freeler integer,
    nombres character varying COLLATE pg_catalog."default" NOT NULL,
    apellidos character varying COLLATE pg_catalog."default" NOT NULL,
    dni character varying COLLATE pg_catalog."default",
    email character varying COLLATE pg_catalog."default",
    telefono character varying COLLATE pg_catalog."default",
    ocupacion character varying COLLATE pg_catalog."default",
    ciudad character varying COLLATE pg_catalog."default",
    descripcion text COLLATE pg_catalog."default",
    origen character varying COLLATE pg_catalog."default" NOT NULL,
    id_estado_lead integer,
    estado_completo boolean DEFAULT false,
    fecha_creacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT leads_pkey PRIMARY KEY (id_lead)
);

CREATE TABLE IF NOT EXISTS freeler.roles
(
    id_rol serial NOT NULL,
    nombre character varying COLLATE pg_catalog."default" NOT NULL,
    descripcion text COLLATE pg_catalog."default",
    CONSTRAINT roles_pkey PRIMARY KEY (id_rol)
);

CREATE TABLE IF NOT EXISTS freeler.usuario_freeler
(
    id_usuario_freeler serial NOT NULL,
    nombres character varying COLLATE pg_catalog."default" NOT NULL,
    apellidos character varying COLLATE pg_catalog."default" NOT NULL,
    dni character varying COLLATE pg_catalog."default" NOT NULL,
    email character varying COLLATE pg_catalog."default" NOT NULL,
    telefono character varying COLLATE pg_catalog."default",
    password character varying COLLATE pg_catalog."default" NOT NULL,
    saldo numeric(10, 2) DEFAULT 0.00,
    estado integer DEFAULT 1,
    fecha_creacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT usuario_freeler_pkey PRIMARY KEY (id_usuario_freeler),
    CONSTRAINT usuario_freeler_dni_key UNIQUE (dni),
    CONSTRAINT usuario_freeler_email_key UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS freeler.usuarios_empresa
(
    id_usuario_empresa serial NOT NULL,
    id_empresa integer,
    id_rol integer,
    nombres character varying COLLATE pg_catalog."default" NOT NULL,
    apellidos character varying COLLATE pg_catalog."default" NOT NULL,
    email character varying COLLATE pg_catalog."default" NOT NULL,
    password character varying COLLATE pg_catalog."default" NOT NULL,
    estado integer DEFAULT 1,
    fecha_creacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT usuarios_empresa_pkey PRIMARY KEY (id_usuario_empresa),
    CONSTRAINT usuarios_empresa_email_key UNIQUE (email)
);

ALTER TABLE IF EXISTS freeler.asignaciones
    ADD CONSTRAINT asignaciones_id_lead_fkey FOREIGN KEY (id_lead)
    REFERENCES freeler.leads (id_lead) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS freeler.asignaciones
    ADD CONSTRAINT asignaciones_id_usuario_empresa_fkey FOREIGN KEY (id_usuario_empresa)
    REFERENCES freeler.usuarios_empresa (id_usuario_empresa) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS freeler.campanias
    ADD CONSTRAINT campanias_id_empresa_fkey FOREIGN KEY (id_empresa)
    REFERENCES freeler.empresas (id_empresa) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS freeler.comisiones
    ADD CONSTRAINT comisiones_id_campania_fkey FOREIGN KEY (id_campania)
    REFERENCES freeler.campanias (id_campania) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS freeler.comisiones
    ADD CONSTRAINT comisiones_id_estado_comision_fkey FOREIGN KEY (id_estado_comision)
    REFERENCES freeler.estado_comisiones (id_estado_comision) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS freeler.comisiones
    ADD CONSTRAINT comisiones_id_lead_fkey FOREIGN KEY (id_lead)
    REFERENCES freeler.leads (id_lead) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS freeler.comisiones
    ADD CONSTRAINT comisiones_id_usuario_freeler_fkey FOREIGN KEY (id_usuario_freeler)
    REFERENCES freeler.usuario_freeler (id_usuario_freeler) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS freeler.leads
    ADD CONSTRAINT leads_id_campania_fkey FOREIGN KEY (id_campania)
    REFERENCES freeler.campanias (id_campania) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS freeler.leads
    ADD CONSTRAINT leads_id_estado_lead_fkey FOREIGN KEY (id_estado_lead)
    REFERENCES freeler.estado_lead (id_estado_lead) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS freeler.leads
    ADD CONSTRAINT leads_id_usuario_freeler_fkey FOREIGN KEY (id_usuario_freeler)
    REFERENCES freeler.usuario_freeler (id_usuario_freeler) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS freeler.usuarios_empresa
    ADD CONSTRAINT usuarios_empresa_id_empresa_fkey FOREIGN KEY (id_empresa)
    REFERENCES freeler.empresas (id_empresa) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS freeler.usuarios_empresa
    ADD CONSTRAINT usuarios_empresa_id_rol_fkey FOREIGN KEY (id_rol)
    REFERENCES freeler.roles (id_rol) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

-- Permitir valores nulos en apellidos de la tabla leads para soportar importaciones parciales
ALTER TABLE IF EXISTS freeler.leads
    ALTER COLUMN apellidos DROP NOT NULL;

-- Catálogo oficial de estados de lead con nombres normalizados
INSERT INTO freeler.estado_lead (id_estado_lead, nombre, descripcion)
VALUES
    (1, 'Pendiente', 'Lead recibido pendiente de revisión'),
    (2, 'Asignado', 'Lead asignado a un vendedor'),
    (3, 'Contactado', 'Lead ya tuvo el primer contacto'),
    (4, 'En gestión', 'Lead en seguimiento activo'),
    (5, 'Perdido', 'Se descartó al lead'),
    (6, 'Ganado', 'Lead convertido en venta')
ON CONFLICT (id_estado_lead)
DO UPDATE
    SET nombre = EXCLUDED.nombre,
        descripcion = EXCLUDED.descripcion;

END;
